### ISSUE TITLE
This algorithm creates artifacts

### ISSUE THREAD

**Issue by computersarecool** [yhjo09/VSR-DUF#10]
Hi @yhjo09 I have been testing your algorithm a lot and I notice artifacts in the result images that are not present in the input images.

Your own repo has a good example of what I am talking about.  In the result image [here](https://github.com/yhjo09/VSR-DUF/blob/master/results/16L/G/calendar/Frame001.png) you can notice green and black artifacts at the top of the image.  This is not present in the original input [here](https://github.com/yhjo09/VSR-DUF/blob/master/inputs/G/calendar/Frame%20001.png)

I notice the same thing on my images while trying every single supported combination of `<R><L>` values.

<img width="1025" alt="Captureaaa" src="https://user-images.githubusercontent.com/5414692/58058707-c53f3500-7b1e-11e9-85f4-f0273b3136a9.PNG">

On some (i.e. `4 52`) the artifacts are on the left of the image.

Your [paper](https://yhjo09.github.io/files/VSR-DUF_CVPR18.pdf) does show full images - did they have the same issue? 

If not how did you solve this issue?

**Comment by mwalczyk** [comment]
Woah! I'm having this _same_ exact issue in my tests as well...

**Comment by Dobatymo** [comment]
I am having artifacts as well (with x4 52 layers). However even stronger.
The top half of the picture is fine, but the bottom one is barely recognizable.
![Frame044](https://user-images.githubusercontent.com/7647594/58075152-8b7f3480-7bd9-11e9-88f4-16b2b6dc47e6.png)

**Comment by yhjo09** [comment]
Hi @computersarecool.
It is because the model trained excluding 8 border pixels.
You can simply pad input frames with 2px, and crop the output border by 8px.

**Comment by yhjo09** [comment]
@Dobatymo 
Do you get strange results even in small size?

**Comment by Dobatymo** [comment]
I don't have these problems when I treat the pictures as ground truth `4 52 G`. But as low resolution with `2 16 L`, `3 16 L`, `4 16 L` I have the same problems as above.
