### ISSUE TITLE
What are the gaussian filter parameters for x2, x3 ?

### ISSUE THREAD

**Issue by stuln2** [yhjo09/VSR-DUF#2]
Hi~Thanks for your greate work and sharing the codes.
I'm using your project and my own data to train video super-resolution X2、X3 and X4 model,
the X4 model works well, but the X2、X3 models don't .
when running the X2、X3 models,  I find that the output residual looks abnormally. 
I notice that you comment "h = gkern(13, 1.6)  # 13 and 1.6 for x4" for the gaussian filter, but I don't change this parameter in the X2、X3 models.
I am wondering if the improper parameter causes the wrong residual.
Would you please tell me what the gaussian filter parameters that you used for training the X2、X3 models?
Thank you very much!

![image](https://user-images.githubusercontent.com/41603953/44777483-5d6e4600-abad-11e8-83aa-c2594171f639.png)
![image](https://user-images.githubusercontent.com/41603953/44777515-6c54f880-abad-11e8-914f-31434ed3a87f.png)

**Comment by zhongtao93** [comment]
@stuln2 did you find the gaussian filter parameters for x2?

**Comment by SinkKathir** [comment]
@stuln2 ,I want train the model on my own datasets too, 
Could you please sent me the code for train,thanks
